### ISSUE TITLE
Playlists w/o custom image not loading

### ISSUE THREAD

**Issue by Satanarious** [duffey/spicetify-playlist-labels#28]
Playlists that don't have custom images but use the 2x2 grid of track art as images are not loading. Atleast in some cases, but sometimes they do load.

- None loading:
![image](https://github.com/duffey/spicetify-playlist-labels/assets/42642682/89f96c80-e823-4312-93b3-40fd7b65d434)

- Partially loading:
![image](https://github.com/duffey/spicetify-playlist-labels/assets/42642682/1b21adc2-128b-455a-addb-f3e7e9d8b756)

>[!Note]
>Both images are from the same playlist & for different tracks and were taken at the same time.

**Comment by duffey** [comment]
Should be fixed. You might need to delete the IndexedDB and reload Spotify.

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/f8299514-bd05-48af-9a12-a9202694cd91)

**Comment by duffey** [comment]
@User094573 Please make a separate issue if you are still having a problem with any info you can give.

**Comment by duffey** [comment]
@Satanarious Please reopen this issue if it's still a problem.

**Comment by Satanarious** [comment]
Didn't fix the problem
![image](https://github.com/duffey/spicetify-playlist-labels/assets/42642682/a359d103-6361-4e0a-9dc1-49e0973cf5af)

**Comment by duffey** [comment]
It seems like the Marketplace version hasn't been updated. I will check back later.

**Comment by Satanarious** [comment]
Still doesn't load. Is this somehow a caching bug?

**Comment by duffey** [comment]
Just to clarify, are the labels showing up, but appear as in the screenshot? Did you delete the IndexedDB and restart? Also, if you see any errors in the dev console please let me know. I will try to reproduce this in the meantime.

**Comment by Satanarious** [comment]
- Yes, the labels show up, but the images don't load for playlists w/o a custom image.
- Yes, I deleted the IndexedDB and restarted; didn't fix the problem.
- No, I dont see any errors in the console.

**Comment by duffey** [comment]
Has this been fixed by the latest update? If not, I need to find out how to reproduce it.

**Comment by duffey** [comment]
I was able to reproduce it, and I think I have fixed it.

**Comment by Satanarious** [comment]
Once my extension updates, I'll let you know if the problem is fixed.

**Comment by Satanarious** [comment]
It's working now, though the mosaic images take more time to load than the rest of the covers on startup, so somehow, those are not getting cached. They will show up correctly after a while, randomly.

**Comment by Satanarious** [comment]
I reopened it because I waited 20 mins, and it didn't load.
